blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on using httpx
    url: https://github.com/projectdiscovery/httpx/discussions/categories/q-a
    about: Ask a question or request support for using httpx

  - name: Share idea / feature to discuss for httpx
    url: https://github.com/projectdiscovery/httpx/discussions/categories/ideas
    about: Share idea / feature to discuss for httpx

  - name: Connect with PD Team (Discord)
    url: https://discord.gg/projectdiscovery
    about: Connect with PD Team for direct communication